package com.utp.unibanco.presentation.card

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import kotlin.random.Random

class CardViewModel : ViewModel() {

    var cardNumber by mutableStateOf("")
        private set

    var cvv by mutableStateOf("")
        private set

    var expiry by mutableStateOf("")
        private set

    var generated by mutableStateOf(false)
        private set

    fun generateCard() {
        cardNumber = generateCardNumber()
        cvv = generateCVV()
        expiry = generateExpiryDate()
        generated = true
    }

    private fun generateCardNumber(): String {
        return (1..4).joinToString(" ") {
            (1..4).joinToString("") { Random.nextInt(0, 9).toString() }
        }
    }

    private fun generateCVV(): String {
        return (1..3).joinToString("") { Random.nextInt(0, 10).toString() }
    }

    private fun generateExpiryDate(): String {
        val month = Random.nextInt(1, 13).toString().padStart(2, '0')
        val year = Random.nextInt(26, 29)
        return "$month/$year"
    }
}